blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/Kyeong6/autolang/discussions
    about: For general questions, use Discussions instead of Issues
